{{- if (include "createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: linode
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
{{- if not .Values.existingSecret }}
stringData:
  token: {{ .Values.apiToken }}
  region: {{  .Values.region }}
type: Opaque
{{- end -}}
{{- end -}}