# Secrets:
# apiToken [Required] - Must be a Linode APIv4 Personal Access Token with all permissions. (https://cloud.linode.com/profile/tokens) 
apiToken: ""

# region [Required] - Must be a Linode region. (https://api.linode.com/v4/regions)
region: ""

# you can also specify the name of an existing Secret
# with keys TOKEN and REGION
existingSecret: ""

# Default namespace is "kube-system" but it can be set to another namespace
namespace: kube-system

# Default storageClass is "linode-block-storage-retain" but it can be set to
# "linode-block-storage" or left as an empty string
defaultStorageClass: linode-block-storage-retain

# Images - Default 
csiProvisioner:
  image: registry.k8s.io/sig-storage/csi-provisioner
  tag: v3.0.0
  pullPolicy: IfNotPresent

csiAttacher:
  image: registry.k8s.io/sig-storage/csi-attacher
  tag: v3.3.0
  pullPolicy: IfNotPresent

csiResizer:
  image: registry.k8s.io/sig-storage/csi-resizer
  tag: v1.3.0
  pullPolicy: IfNotPresent

csiLinodePlugin:
  image: linode/linode-blockstorage-csi-driver 
  tag: v0.5.0
  pullPolicy: IfNotPresent

kubectl:
  image: bitnami/kubectl
  tag: 1.25.6-debian-11-r7

csiNodeDriverRegistrar:
  image: registry.k8s.io/sig-storage/csi-node-driver-registrar
  tag: v1.3.0
